version: '3.8'
services:
  nginx:
    env_file: .env
    image: nginx:stable-alpine
    ports:
      - ${PORT}:80
    volumes:
      - ./app:/var/www/html # Mount your Yii2 project into the container
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Nginx configuration
    depends_on:
      - php-fpm
  php-fpm:
    env_file: .env
    image: yiisoft/yii2-php:8.2-fpm # Official Yii2 PHP-FPM image or a custom one
    volumes:
      - ./app:/var/www/html
    environment:
      # Optional: Define environment variables for Yii2 (e.g., for database connection)
      - DB_DSN=mysql:host=mysql;dbname=your_db_name
      - DB_USERNAME=sql_user
      - DB_PASSWORD=sql_user_password
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0 # Or another MySQL version
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test
      MYSQL_USER: sql_user
      MYSQL_PASSWORD: sql_user_password
    volumes:
      - ./mysql-data:/var/lib/mysql # Persistent storage for MySQL data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Optional: Initial database setup script